server:
  port: 8089
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 15017814621
    url: jdbc:mysql://localhost:3306/dboa?characterEncoding=UTF-8&serverTimezone=GMT%2B8

